name: cross_attention_cnn
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip>=21.0
  - numpy=1.23.5  # Keeping below 1.24 for CUDA compatibility
  - pandas>=1.3.0
  - matplotlib>=3.4.0
  - seaborn>=0.11.0
  - opencv>=4.5.0
  - tensorflow=2.10.0  # Compatible with Python 3.9 and numpy<1.24
  - tensorflow-gpu=2.10.0  # GPU support
  - cudatoolkit=11.2  # Compatible with TF 2.10
  - cudnn=8.1.0  # Compatible with cudatoolkit 11.2
  - pyyaml>=6.0
  - scikit-learn>=1.0.0
  - tqdm>=4.62.0
  - jupyterlab>=3.2.0
  - ipywidgets>=7.6.0
  - scipy>=1.7.0
  - pip:
    - wandb>=0.12.0
    - mtcnn>=0.1.0
    - keras-cv>=0.4.0  # For computer vision tasks
    - albumentations>=1.1.0
